ns="Compiler"
package="Idris2Grin"
version="0.0.1"

modules = [
    "GRIN.ANFToGRIN",
    "GRIN.Data",
    "GRIN.GrinCG",
    "GRIN.PrimOps",
    "Main"
    ]

depends = ["idris2", "contrib", "network"]
sourcedir = "src"
main = "Main"
executable = "idris2grin"

[[extra-dep]]
download="folder"
url="grin"
