name:                grinIdris2
version:             0.1.0
# github:              "githubuser/grinIdris2"
# license:             BSD3
# author:              "Author name here"
# maintainer:          "example@example.com"
# copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/grinIdris2#readme>

dependencies:
- base >= 4.7 && < 5
- grin
- megaparsec == 7.*
- filepath
- text

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  grinIdris2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grinIdris2

tests:
  grinIdris2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grinIdris2
