ns="Compiler"
package="Grin"
version="0.0.1"

modules=[
    "Data.SortedMap.Extra",
    "Data.String.Builder",
    "Data.String.Utils",
    "GRIN.Analysis.CallGraph",
    "GRIN.Analysis.Inline",
    "GRIN.Analysis.MaxVar",
    "GRIN.Opts.CaseSimplify",
    "GRIN.Opts.CopyPropogation",
    "GRIN.Opts.Inline",
    "GRIN.Opts.NormaliseBind",
    "GRIN.Opts.UnusedConstructorElim",
    "GRIN.Opts.UnusedFunctionElim",
    "GRIN.Opts.UnusedParameterElim",
    "GRIN.Opts.UnusedVarElim",
    "GRIN.AST",
    "GRIN.Error",
    "GRIN.GrinM",
    "GRIN.GrinState",
    "GRIN.Name",
    "GRIN.Parser",
    "GRIN.Pipeline",
    "GRIN.Pretty",
    "GRIN.PrettyCompat",
    "GRIN.PrettyCompatB",
    "GRIN.ToLLVM",
    "GRIN.Var",
    "LLVM.AST",
    "LLVM.Pretty"
    ]

depends = ["contrib"]
sourcedir = "src"
